### ISSUE TITLE
Improve the way auto data is stored

### ISSUE THREAD

**Issue by ajayyy** [LakeEffectRobotics/LakeEffectScoutingApp#119]
Something more averagable, would be useful for Tableau.

**Comment by gregk27** [comment]
I don't want to change it because of what happened last year

**Comment by ajayyy** [comment]
Ok, I remember you mentioning in scouting meeting something about changing it so I made this issue

**Comment by gregk27** [comment]
Oh in average ya, i thought you meant in main app

**Comment by ajayyy** [comment]
Oh ok, I thought you wanted the main app to be more like averages. So instead of the rule and fail or success, you have own switch success, scale success etc. But it's fine because we can just use the averaged file for that.
