### ISSUE TITLE
Update robot list for fall fiesta

### ISSUE THREAD

**Issue by gregk27** [LakeEffectRobotics/LakeEffectScoutingApp#125]

**Comment by ajayyy** [comment]
This might not be necessary if we successfully do https://github.com/LakeEffectRobotics/LakeEffectScoutingApp/issues/126

**Comment by ajayyy** [comment]
Needs to be done just in case in a branch

**Comment by ajayyy** [comment]
https://github.com/LakeEffectRobotics/LakeEffectScoutingApp/tree/ff2018

Removed in new code
