### ISSUE TITLE
Fix issues with getting id to check if something exists

### ISSUE THREAD

**Issue by ajayyy** [LakeEffectRobotics/LakeEffectScoutingApp#129]
The line below throws an error according to Android Studio. The app still runs and functions fine though.

```java
 if (v.getId() > 0) {
```

**Comment by gregk27** [comment]
i think it is used so we dont call getbyId on items without id or vice versa

**Comment by ajayyy** [comment]
Removed the if statement as it was unneeded anyway. We might need to revisit this issue if something breaks as a result of this fix.
