### ISSUE TITLE
Put only one button on the front of the cargo ship

### ISSUE THREAD

**Issue by ajayyy** [LakeEffectRobotics/LakeEffectScoutingApp#189]
Is it necessary to know between the two?

**Comment by gregk27** [comment]
For hatches it could be

**Comment by gregk27** [comment]
Cargo isn't

**Comment by ajayyy** [comment]
Why would it matter for hatches?

**Comment by gregk27** [comment]
Some mechanisms will be faster at one side

**Comment by gregk27** [comment]
Like for us, we don't need to spin to score on far side, so if someone can do close side fast, they're a better match

**Comment by ajayyy** [comment]
This is the cargo ship, not the rocket

**Comment by gregk27** [comment]
oh.
Then as long as it won't cause confusion go for it
