### ISSUE TITLE
Correctly count non attempts in averages

### ISSUE THREAD

**Issue by ajayyy** [LakeEffectRobotics/LakeEffectScoutingApp#193]
Did not try climbing for example

**Comment by gregk27** [comment]
There can be as many sections as you want

**Comment by gregk27** [comment]
You can have HAB3 | HAB2 | HAB1 | No attempt

**Comment by ajayyy** [comment]
This is fine in the UI (I can show you the new inputting system we did for that Monday), but when we do averages, we should take this into account. At the moment we usually forget

**Comment by gregk27** [comment]
IDK, and likely wont until after week 1

**Comment by ajayyy** [comment]
We decided on doing two spinners for climbing. One for the level (1, 2, 3,
parked), one for attempt (no attempt, failed, carried, success)
