### ISSUE TITLE
Add unsent data notifications

### ISSUE THREAD

**Issue by gregk27** [LakeEffectRobotics/LakeEffectScoutingApp#21]
- [x] Send notification at set time (5pm?)
- [x] Notification contents
    - [x] Amount of unsent messages
    - [x] Message with instructions to contact manager

**Comment by ajayyy** [comment]
Update, event soon.

**Comment by ajayyy** [comment]
https://firebase.google.com/docs/cloud-messaging/android/send-multiple

**Comment by ajayyy** [comment]
@Aree-Vanier is this done?
